apiVersion: apps/v1
kind: Deployment
metadata:
  name: udayvarma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udayvarma
  template:
    metadata:
      labels:
        app: udayvarma
    spec:
      containers:
        - name: udayvarma
          image: 410129828206.dkr.ecr.us-west-2.amazonaws.com/udayvarma77:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: udayvarma
  labels:
    app: udayvarma
spec:
  selector:
    app: udayvarma
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
