apiVersion: apps/v1
kind: Deployment
metadata:
  name: udayvarma-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udayvarma
  template:
    metadata:
      labels:
        app: udayvarma
    spec:
      containers:
      - name: udayvarma
        image: '410129828206.dkr.ecr.us-west-2.amazonaws.com/udayvarma77
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udayvarma
    k8s-app: udayvarma
  name: udayvarma
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: udayvarma
